INSERT INTO events (eventDate, eventDescription) VALUES
('October 12, 2019', 'First Met'),
('September 21, 2020', 'Reassignment List'),
('November 16, 2020', 'First time I stayed late'),
('November 25, 2020', 'Started texting'),
('December 7, 2020', 'Told her I liked her'),
('March 28, 2021', 'First hug?'),
('April 28, 2021', 'Went to her house, met Nala'),
('June 26, 2021', 'First long hug, First time saying “I love you” in person'),
('September 7, 2021', 'First time driving her home from school'),
('October 23, 2021', 'Met Mom and Dad at pinball show'),
('October 25, 2021', 'First kiss'),
('November 5, 2021', 'Rubber bands!'),
('November 25, 2021', 'Started dating'),
('December 7, 2021', 'First time hanging out in my apartment'),
('December 23, 2021', 'Gave us our matching bracelets'),
('January 3, 2022', 'Celebrated my birthday that night after she got back from Arizona'),
('January 15, 2022', 'Went and saw Spider-Man NWH'),
('March 21, 2022', 'Assembled furniture in my living room'),
('March 24, 2022', 'Came to the springs, met Rose at lunch and went bowing with mom and dad'),
('April 22, 2022', 'Came to the house with me to put Roger down, went to lunch at Fargos with mom, dad, and Rose'),
('April 23, 2022', 'Went to her house and had pizza with her and her mom, watched Princess Bride'),
('April 26, 2022', 'Visited me during her off periods after I threw up, then hung out after school for awhile, first time making out'),
('May 14, 2022', 'Yard sale day! Hungout with her, her mom, and neighbors all day :)'),
('May 19, 2022', 'Dinner with her grandparents'),
('May 21, 2022', 'Graduation party! (Best Day Ever) Got to meet pretty much everybody and talk to her family all day long, even stayed late for dinner and wii bowling'),
('May 25, 2022', 'Six month anniversary! Went to the springs to get me a filling and see my parents. Sadly, my baby was sick with the flu, had to drive her back and take her to the hospital :('),
('June 4, 2022 & June 19, 2022', 'Picked her up from DIA and drove her home to Jason’s, really sad after having to leave her mom'),
('June 29, 2022', 'First time spending the night together, slept together in her bed at Jason’s'),
('July 9, 2022', 'Roses baby shower! She met uncle Damon, Aunt Val, Nathan, Joey, Heidi and Bob'),
('July 23, 2022', 'Went to Nathan and Catherine’s wedding, Olive Garden with Rose afterwards'),
('July 24, 2022', 'Moving day! Worked with my parents to get me moved to new apartment in Longmont'),
('August 6, 2022', 'Left Colorado to drive with her to move to Tucson. Made it to Albuquerque to sleep together at the hotel'),
('August 13, 2022', 'The day that I really, really hoped would never come. I left Arizona to come back to Colorado, we now live in different states, 1000 miles apart'),
('September 2, 2022 - September 5, 2022', 'She visited us in Colorado for Labor Day weekend, crazy airport stuff including both flights delayed 2+ hours');